apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webappone
  name: webappone-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webappone
  template:
    metadata:
      labels:
        app: webappone
    spec:
      containers:
      - image: quay.io/thiha0000/demoapp:v1
        name: webappone
