apiVersion: v1
kind: Service
metadata:
  labels:
    app: webappone
  name: webappone-svc
spec:
  ports:
  - name: webappone-ports
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: webappone
  type: NodePort
