apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: webappone
  namespace: argocd
spec:
  destination:
    namespace: webappone
    server: https://kubernetes.default.svc
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
  source:
    path: declarative_demo/apps/webappone
    repoURL: https://github.com/thiha1010/argo-cd.git
    targetRevision: HEAD
  project: default
