apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp
  name: demodep
  namespace: demons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - image: quay.io/thiha0000/demoapp:v1
        name: demoapp