apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: demoapp
  name: demodep
  namespace: demons
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demoapp
  template:
    metadata:
      labels:
        app: demoapp
    spec:
      containers:
      - image: demo/argoCD/demo-1-app/deployment.yaml:v1
        name: demoapp