apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: kustomize-demo

resources:
  - namespace.yaml
  - deployment.yaml
  - service.yaml

namePrefix: kustomize-

commonLabels:
  env: development