apiVersion: v1
kind: Service
metadata:
  labels:
    app: demoapp
  name: demoapp-svc
  namespace: demoapp
spec:
  ports:
  - name: demoapp-ports
    nodePort: 31000
    port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: demoapp
  type: NodePort
