apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: webapp2
  name: webapp2-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp2
  template:
    metadata:
      labels:
        app: webapp2
    spec:
      containers:
      - image: quay.io/thiha0000/demoapp:v2
        name: webapp2
